---
# - name: Copy postgres-exporter config
#   template:
#     src: exporter-metrics.yaml.j2
#     dest: /etc/exporter-metrics.yml

- name: Create postgres exporter container
  docker_container:
    name: postgres-exporter
    image: "wrouesnel/postgres_exporter:latest"
    links:
    - "postgresql:postgresql"
    # entrypoint: [ "/postgres_exporter", "--extend.query-path=/metrics.yml" ]
    env:
      DATA_SOURCE_URI: "postgresql:5432/?sslmode=disable"
      DATA_SOURCE_USER: "{{ db_user }}"
      DATA_SOURCE_PASS: "{{ db_pass }}"
    # volumes:
    # - "/etc/exporter-metrics.yaml:/metrics.yml:ro"
